title = "Azure Citadel"
theme = "citadel"

[menu]

  # Home -> Sections

  [[menu.section]]
    name = "Azure Policy"
    url = "/policy"

  [[menu.section]]
    name = "About"
    url = "/about"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = false
    tabWidth = 2